### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Node has 0 height.

### ISSUE THREAD

**Issue by shenjing023** [transitive-bullshit/puppeteer-lottie#37]
Hi,
This package is great, thanks!

There are some error when I set renderer = "html",
```js
await renderLottie({
    path: "data.json",
    output: "data.mp4",
    ffmpegOptions: {
      crf: 30,
      profileVideo: "main",
      preset: "superfast",
    },
    width: 368,
    height: 640,
    renderer: "html",
  });
```
And it will report some error:
```
(node:5700) UnhandledPromiseRejectionWarning: Error: Node has 0 height.
    at assert (C:\ml\zishuo\node_modules\puppeteer\lib\helper.js:283:11)
    at ElementHandle.screenshot (C:\ml\zishuo\node_modules\puppeteer\lib\JSHandle.js:441:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ElementHandle.<anonymous> (C:\ml\zishuo\node_modules\puppeteer\lib\helper.js:111:15)
    at module.exports (C:\ml\zishuo\node_modules\puppeteer-lottie\index.js:366:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Is this something error in Pupeteer? Thanks for any help!

**Comment by vinay360** [comment]
Hey did you find the solution because I am facing the same issue

**Comment by shenjing023** [comment]
no, maybe you should find other repo in github
